"""
URGENT: Verify Google AI rate limit type
- Per-project (shared across all keys)
- Per-key (independent for each key)
"""

print("🔍 GOOGLE AI RATE LIMIT TYPE VERIFICATION")
print("="*70)

print("\n📋 QUESTION:")
print("   Với 11 keys trong CÙNG 1 project, rate limit được tính:")
print("   A. PER-PROJECT: 5 RPM total (chia sẻ giữa 11 keys)")
print("   B. PER-KEY: 5 RPM × 11 = 55 RPM total (mỗi key độc lập)")

print("\n🌐 THEO GOOGLE DOCUMENTATION:")
print("   URL: https://ai.google.dev/gemini-api/docs/rate-limits")
print()
print("   Free tier limits are applied PER PROJECT:")
print("   - gemini-2.5-flash: 5 RPM per PROJECT ⚠️")
print("   - gemini-2.0-flash: 15 RPM per PROJECT ⚠️")
print()
print("   Multiple API keys trong CÙNG project:")
print("   → Chia sẻ CHUNG rate limit!")
print("   → Không tăng RPM!")

print("\n🔴 IMPACT:")
print("   Nếu rate limit là PER-PROJECT:")
print("   - 11 keys × 5 RPM = 5 RPM (NOT 55 RPM!)")
print("   - Optimal threads: 4 (NOT 44!)")
print("   - Multiple keys CHỈ để:")
print("     • Failover khi 1 key lỗi")
print("     • Vượt quota 1 key (RPD)")
print("     • KHÔNG tăng throughput!")

print("\n✅ SOLUTION:")
print("   Nếu muốn 55 RPM:")
print("   → Cần tạo 11 PROJECTS khác nhau")
print("   → Mỗi project có 1 key")
print("   → Mỗi project có rate limit riêng")

print("\n🧪 TEST RECOMMENDATION:")
print("   Để verify, hãy test:")
print("   1. Dùng 2 keys từ CÙNG project")
print("   2. Gửi 10 requests đồng thời (5 per key)")
print("   3. Nếu PER-PROJECT: Sẽ bị rate limit sau 5 requests")
print("   4. Nếu PER-KEY: Tất cả 10 requests OK")

print("\n" + "="*70)
print("⚠️  USER REPORT:")
print("="*70)
print("   User nói: 'RPM của google tính theo toàn cục'")
print("   User nghĩ: '1 phút chỉ được gửi 4 request với model 2.5'")
print()
print("   → User có thể ĐÚNG!")
print("   → Code hiện tại giả định PER-KEY (SAI!)")
print("   → Cần fix NGAY!")
print("="*70)

print("\n🔧 IMMEDIATE ACTION:")
print("   1. Verify với user: Tất cả 11 keys có từ CÙNG 1 project?")
print("   2. Nếu YES → Fix code:")
print("      - Threads = 4 (không nhân với số keys)")
print("      - Keys chỉ dùng để rotate (failover)")
print("      - Rate limiter: GLOBAL cho tất cả keys")
print("   3. Nếu NO (11 projects khác nhau) → Code hiện tại OK")

print("\n💡 RECOMMENDED ARCHITECTURE:")
print("   Option 1: Multiple Projects (BEST)")
print("   - 11 Google Cloud projects")
print("   - 1 API key per project")
print("   - Total: 55 RPM ✅")
print()
print("   Option 2: Single Project (CURRENT)")
print("   - 1 Google Cloud project")
print("   - 11 API keys (same project)")
print("   - Total: 5 RPM ⚠️")
print("   - Keys only for failover")

print("\n❓ WAITING FOR USER CONFIRMATION:")
print("   'Tất cả 11 keys của bạn có từ CÙNG 1 project không?'")
print("="*70)
